### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by kachkaev** [remarkjs/remark-lint#168]
I just noticed that pages like
* [packages/remark-lint-checkbox-character-style/readme.md](https://github.com/remarkjs/remark-lint/tree/ddfad50650ee282d8ea3d8a8811039a3527c2e85/packages/remark-lint-checkbox-character-style/readme.md)
* [packages/remark-lint-code-block-style/readme.md](https://github.com/remarkjs/remark-lint/tree/ddfad50650ee282d8ea3d8a8811039a3527c2e85/packages/remark-lint-code-block-style/readme.md)
* [packages/remark-lint-emphasis-marker/readme.md](https://github.com/remarkjs/remark-lint/tree/ddfad50650ee282d8ea3d8a8811039a3527c2e85/packages/remark-lint-emphasis-marker/readme.md)

contain broken links in _Using remark to fix your markdown_. These point to  
https://github.com/remarkjs/remark-lint/tree/formatting#using-remark-to-fix-your-markdown  
while the right URL is probably  
https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown

Not submitting a PR as I'm not sure if I guessed the right address.

**Comment by wooorm** [comment]
Sweet, thanks for raising an issue!
