### ISSUE TITLE
Default behavior for `remark-lint-linebreak-style`

### ISSUE THREAD

**Issue by Planeshifter** [remarkjs/remark-lint#175]
`remark-lint-linebreak-style` breaks down when one explicitly sets the option to `consistent`, as L74 in https://github.com/remarkjs/remark-lint/blob/master/packages/remark-lint-linebreak-style/index.js only checks whether `preferred` is truthy. In other rules, you have used the following pattern at the beginning of the function body:

```js
preferred = typeof preferred !== 'string' || preferred === 'consistent' ? null : preferred;
```

Alternatively, one could explicitly check for whether `preferred` is equal to `unix` or `windows` in L74.

**Comment by wooorm** [comment]
Ohh right, thanks for letting me know!

Would you be interested in fixing it?

**Comment by Planeshifter** [comment]
Sure, I can create a pull request.

**Comment by wooorm** [comment]
Sweet, thanks Philipp!

**Comment by kgryte** [comment]
@wooorm Would you mind publishing the patched version of this rule to `npm`? :)

**Comment by wooorm** [comment]
@kgryte @Planeshifter Sorry it took so long! 😬 Finally released!
