### ISSUE TITLE
\r\n problem in maximum-line-length.js for previous releases (versions 5.x.x)

### ISSUE THREAD

**Issue by bessorion** [remarkjs/remark-lint#179]
Hi, there are problem with line-endings in maximum-line-length.js vor version 5. 
Please see https://github.com/qmlweb/qmlweb/issues/435 for details.
This problem still actual in the latest 5.4.0 also.
I suppose it would be great to release some updates (f.e. 5.4.1) for those who cannot migrate to 6 version right now.

**Comment by wooorm** [comment]
My gut tells me not a lot of people use the older versions. 🤷‍♂️
Why not update the package instead?

**Comment by bessorion** [comment]
@wooorm Sometimes it requires many additional efforts
