### ISSUE TITLE
remark refuses to fix files with "-o"

### ISSUE THREAD

**Issue by GrayedFox** [remarkjs/remark-lint#180]
Hiya,

I am trying to fix a specific file using remark, since it comes bundled with remark-stringify and the only things breaking the rules are the tables (very annoying to fix by hand). 

Here is my config:

```json
{
  "plugins": {
    "lint-maximum-line-length": ["error", 80],
    "lint-code-block-style": ["error", "fenced"],
    "lint-emphasis-marker": ["error", "*"],
    "lint-file-extension": ["error", "md"],
    "lint-final-newline": ["error"],
    "lint-final-definition": ["error"],
    "lint-first-heading-level": ["error", 1],
    "lint-heading-increment": ["error", 1],
    "lint-heading-style": ["error", "atx"],
    "lint-linebreak-style": ["error", "unix"],
    "lint-no-consecutive-blank-lines": ["error"],
    "lint-no-duplicate-definitions": ["error"],
    "lint-no-duplicate-headings": ["warn"],
    "lint-no-emphasis-as-heading": ["error"],
    "lint-no-empty-url": ["error"],
    "lint-no-file-name-mixed-case": ["error"],
    "lint-no-file-name-irregular-characters": ["error"],
    "lint-no-heading-content-indent": ["error"],
    "lint-no-heading-indent": ["error"],
    "lint-no-heading-punctuation": ["error"],
    "lint-no-literal-urls": ["error"],
    "lint-no-inline-padding": ["error"],
    "lint-no-paragraph-content-indent": ["error"],
    "lint-no-shell-dollars": ["error"],
    "lint-no-tabs": ["error"],
    "lint-no-unused-definitions": ["error"],
    "lint-no-missing-blank-lines": ["error"],
    "lint-ordered-list-marker-style": ["error", "."],
    "lint-strong-marker": ["error", "*"],
    "lint-ordered-list-marker-value": ["error", "one"],
    "lint-unordered-list-marker-style": ["error", "-"],
    "lint-table-cell-padding": ["error", "padded"],
    "lint-table-pipe-alignment": ["error"],
    "lint-table-pipes": ["error"]
  },
  "settings": {
    "emphasis": "*",
    "strong": "*",
    "incrementListMarker": false
  }
}
```

This is the command I'm running:

```
yarn remark ./docs/en/tech/apps/mcon/readme.md --output --rc-path ./.remarkrc.json
```

So, as you can see from the command, possibly important info:
1. I installed remark using yarn, and so run it via yarn
2. I use a custom-named remark config file in order to get proper syntax highlighting via Atom

Things I've tried:
- moving `--output` to the end of the command
- running remark directly with `./node_modules/.bin/remark`

I can confirm the output switch works, since when I pass a custom name a new file is indeed written - the problem is the "written" message never appears in the console and remark-stringify never actually changes the file (all content is the same)

**Comment by GrayedFox** [comment]
Hmm, so, after fixing the docs by hand and running the command again, it seems that the remark-stringify will attempt to rewrite fails that are already somewhat formatted, and just fail silently with no output or stacktrace as to why if it can't fix a file.

would be great to see why and how it's failing - it also doesn't seem to respect some defaults - i.e. `options.fences` apparently defaults to back ticks, but when I run remark with the output switch, it replaces all my lovely multi-line codeblocks with an indent, so this:

> ```
> code
> ```

Becomes
>
>    code
>

**Comment by wooorm** [comment]
remark-lint has no fix capabilities. remark however has some, see the section on [using remark to fix your markdown](https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown) in the readme.

You may also be interested in reading the readme of [`remark-stringify`](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#api).

**Comment by asbjornu** [comment]
@wooorm, is it possible to accomplish markdown fixing via the command line as well?

**Comment by wooorm** [comment]
This issue is about the CLI, however, my previous comment explains that the behavior is limited
