### ISSUE TITLE
Configurable tab size

### ISSUE THREAD

**Issue by AlexWayfer** [remarkjs/remark-lint#181]
Hello!

Tab size (4 by default) for some rules (like `list-item-indent`) should be configurable (I want to set `2`, somebody may want to set `8`).

Thanks.

**Comment by wooorm** [comment]
@AlexWayfer Hey Alex!

That’s not really the way markdown works, in the case of 8. Markdown is not white-space insensitive.

What you mean by `2` is already configurable with [`'space'`](https://github.com/remarkjs/remark-lint/tree/ab7a47bbe5d11c64224a2f82dfc27d34672366c8/packages/remark-lint-list-item-indent#validmd-2).

**Comment by AlexWayfer** [comment]
OK, thanks, I'll try. But `space` is non-intuitive name for 2 spaces.
