### ISSUE TITLE
any guide on creating a team own preset within an NPM scope?

### ISSUE THREAD

**Issue by ahmadnassri** [remarkjs/remark-lint#183]
I couldn't find any docs on whether npm scoped presets are supported, and what -if any- shortcut name to use in the config file?

**Comment by wooorm** [comment]
Hey! There’s no real guide for it. on [npm](https://www.npmjs.com/search?q=remark-preset), there are a few patterns going around (where `alpha` is the company name):

* `remark-preset-alpha`
* `remark-preset-lint-alpha`
* `@alpha/remark-preset`

I suggest a) or c), whatever works for you. b) is too limited to just including stuff from `remark-lint`, You may also want to add other stuff, as [i do with `remark-preset-wooorm`](https://github.com/wooorm/remark-preset-wooorm).

**Comment by ahmadnassri** [comment]
@wooorm thank you, that is the plan, creating a team-wide configuration with some customization, I'm opting for the scoped package approach, but for some reason it's throwing errors with `remark-cli`

```json
{
  "plugins": [
    "@telus/remark-preset-lint-markdown"
  ]
}
```

**Comment by wooorm** [comment]
Super! ✨
