### ISSUE TITLE
Remark not picking up configuration 

### ISSUE THREAD

**Issue by areohbe** [remarkjs/remark-lint#187]
I thought #165 might have the answer but this seems limited to global installs.

My project setup is: 

`package.json`

```
{
  "scripts": {
    ...
    "lint-md": "remark ../docs/getting-started.md"
  },
  "devDependencies": {
    ...
    "remark-cli": "^5.0.0",
    "remark-lint": "^6.0.2",
    "remark-preset-lint-recommended": "^3.0.2",
    ...
  },
...
}
```

`.remarkrc`
```
{
  "plugins": [
    "remark-preset-lint-recommended"
  ]
}
```

When I run `lint-md` it doesn't look like my `.remarkrc` is getting picked up. I also tried configuring it directly in `package.json` but same result.

[Debug Log](https://gist.github.com/areohbe/c380afbff99c9d89dd00e5a10e20c8a6)

**Comment by wooorm** [comment]
@areohbe Correct, remark picks up configuration files from the file and up, but your `package.json` and `.remarkrc` are in a different path.
The solution is to place them both one level up, or place the docs inside a directory with a `.remarkrc` file!

**Comment by areohbe** [comment]
@wooorm thanks! Moving the `.remarkc` to docs folder returns error. I am guessing because now it's in a different directory than `package.json` and can't locate the plugin inside  `npm_modules`.

Is there any way to handle this? Or do `package.json`and `.remarkc` both need to me to be inside the same top level directory as my content?

**Comment by wooorm** [comment]
The remarkrc needs to be in the directory of a file, or in a directory higher.
The remarkc file references plugins by path, similar to how nodes require works, so you can do '../some-path/node_modules/some- plugin' as well!

**Comment by areohbe** [comment]
Moved some things around but still no errors returned.

Now my project looks like:

```
project/
├── website/
│   ├── package.json
│   └── node-modules/
└── docs/
    ├── .remarkrc
    ├── root.md
    └── bar/
        ├── bar1.md
        └── bar2.md
```

and my .remarkrc looks like:
```
{
  "plugins": [
    "../website/node_modules/remark-preset-lint-recommended"
  ]
}
```

**Comment by Murderlon** [comment]
If you separate docs from your site, you might want to split the logic as well.
Perhaps create a new `package.json` with the `remark` packages and `lint-md` script.
```
project/
├── website/
│   ├── package.json
│   └── node-modules/
└── docs/
    ├── package.json
    ├── node-modules/
    ├── .remarkrc
    ├── root.md
    └── bar/
        ├── bar1.md
        └── bar2.md

```
The above should work.

**Comment by areohbe** [comment]
Thanks @Murderlon - this is what I ended up doing. In hindsight, I like this approach. I can keep all content related modules inside `/docs` and all the app modules inside `/website`.

**Comment by woof1234** [comment]
Who r u?

Sent from my iPhone

On 11 Oct 2018, at 11:50 pm, Rob Silverii <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @Murderlon<https://github.com/Murderlon> - this is what I ended up doing. In hindsight, I like this approach. I can keep all content related modules inside /docs and all the app modules inside /website.
