### ISSUE TITLE
Option to remove ascii codes in message?

### ISSUE THREAD

**Issue by laran** [remarkjs/remark-lint#188]
Is there an option to remove the ascii codes in the message returned by require('vfile-reporter').report(..) is called?

**Comment by wooorm** [comment]
@laran That’s a question for vfile-reporter, and can be done through [it’s color option](https://github.com/vfile/vfile-reporter#readme)!

**Comment by laran** [comment]
Thanks! I actually got what I needed by using broke-reporter-json and pulling the message out of that.
