### ISSUE TITLE
Add rule to prefer collapsed references over full ones

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-lint#192]
`[Remark][remark]` -> `[Remark][]`

**Comment by wooorm** [comment]
For a name I’m thinking about `remark-lint-collapsed-references`, but not sure... It’s not perfect.

**Comment by wooorm** [comment]
@ChristianMurphy @ChristianMurphy I’m not sure about a name, WDYT?

**Comment by ChristianMurphy** [comment]
🤔 some more ideas `remark-lint-prefer-compact-reference` or `remark-lint-no-unnecassary-full-reference`.

**Comment by wooorm** [comment]
For `remark-lint-no-unnecassary-full-reference` I’d prefer to use `unneeded` instead. It’s more easily spelled correctly (as the typo in `unnecassary` shows 😉)
