### ISSUE TITLE
Example in README doesn't work?

### ISSUE THREAD

**Issue by larsks** [remarkjs/remark-lint#195]
The README suggests:

```
npm install remark-lint
npm run lint-md
```

But this results in:

```
npm ERR! path /my/cwd/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/my/cwd/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lars/.npm/_logs/2018-12-20T19_01_55_858Z-debug.log
```

And if I try to install it globally with:

```
npm install -g remark-lint
```

There is nothing matching `lint-md` installed into the npm global prefix (and `npm run lint-md` fails in the same way).

If I create an npm project by running `npm init` and then `npm install remark-lint`, the `npm run lint-md` fails with:

```
npm ERR! missing script: lint-md

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lars/.npm/_logs/2018-12-20T19_05_35_276Z-debug.log
```

**Comment by wooorm** [comment]
@larsks I believe [Christian’s response](https://github.com/remarkjs/remark-lint/issues/195#issuecomment-449108827) should answer your question so I’m closing this. But feel free to ask a follow up question if it doesn‘t.

**Comment by larsks** [comment]
I'm all set, thanks!
