### ISSUE TITLE
no-file-name-irregular-characters: allow _ by default ?

### ISSUE THREAD

**Issue by gpotter2** [remarkjs/remark-lint#198]
Hello & thanks for this wonderful tool,

A lot of universal files require to have a `_` in their name, especially with [GitHub’s repository templates](https://github.blog/2016-02-17-issue-and-pull-request-templates/)
I’ve read the (rather short) [rational](http://www.cirosantilli.com/markdown-style-guide/#file-name) behind `_` being excluded, but it seems GitHub people haven’t :/

Those are super common in OpenSource projects, and will raise a warning due to 
[remark-lint-no-file-name-irregular-characters](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-no-file-name-irregular-characters)

It might be a good idea to add `_` to the default regex. Or if that’s not possible, could it be worth adding an exclusion for those 3 files ?

### Github templates full list:

> You can put CONTRIBUTING.md, SUPPORT.md, CODE_OF_CONDUCT.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected.

(Only the ones with `_` cause trouble)

PS: we’re using this project through Codacy, so I don’t think we have access to the config of packages (we can however disable this package, but that’s only a workaround)

**Comment by Murderlon** [comment]
Hi @gpotter2, thanks for the elaborate issue. Afaik `_` is intentionally disallowed here as the default and the optional string or regex is for those that want to deviate.

I haven't used Codacy so I'm sure if you can pass configurations, but wouldn't the easiest thing here to ignore the `.github/` folder?

**Comment by wooorm** [comment]
Did you know that `code-of-conduct.md` also works? Can’t find the docs for that, or whether it works for templates, but maybe try that?

> PS: we’re using this project through Codacy, so I don’t think we have access to the config of packages (we can however disable this package, but that’s only a workaround)

Hmm, I agree with what @Murderlon said above. remark-lint supports configuration, which makes a lot of sense for style guides, so I feel like it’s more of a bug with Codacy if they don’t support configuration 🤷‍♂️

**Comment by gpotter2** [comment]
Thanks for both of your answers, I’ll check all of that.

**Comment by baynezy** [comment]
@gpotter2 - how did you resolve this? I have been unsuccessful.

**Comment by gpotter2** [comment]
I got bored, disabled this test and moved on. It's crazy to forbid `_` 😄 
But this might have been changed by now, I have no idea.

**Comment by da-edra** [comment]
It hasn't changed, I came to this issue looking on how to disable it. I'm automatically generating documentation from my code and it complains of the file names what follow the conventions of the programming language I'm using, this rule makes no sense.

**Comment by wooorm** [comment]
folks we’ve had this conversation. It’s configurable. I’m locking this post.
