### ISSUE TITLE
integration with retext-spell and similar libs

### ISSUE THREAD

**Issue by stephenmoloney** [remarkjs/remark-lint#201]
Hi, this lib is quite a find, thank you!

Is it possible to run `retext-spell` and similar `retext` libs with `remark-cli`
using just a `.remarkrc` file with a list of plugins ?

**Comment by ChristianMurphy** [comment]
It's possible using `unified` programmatically with `remark-text`

```js
var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var parse = require('remark-parse')
var stringify = require('remark-stringify')
var remark2retext = require('remark-retext')
var english = require('retext-english')
var spell = require('retext-spell')

unified()
  .use(parse)
  .use(
    remark2retext,
    unified()
      .use(english)
      .use(spell)
  )
  .use(stringify)
  .process(vfile.readSync('example.md'), function(err, file) {
    console.error(report(err || file))
  })
```

https://github.com/remarkjs/remark-retext

I'm not aware of a `.remarkrc` only solution that exists today.
But that could be something the a new or enhanced plugin may be able to handle.

**Comment by stephenmoloney** [comment]
@ChristianMurphy 

Thanks for outlining this possibility.

I'm really looking for a cli friendly integrated approach to be used as part of a ci pipeline.

**Comment by ChristianMurphy** [comment]
@stephenmoloney for that there is the option of creating a preset:
Which could look something like:

_remark-preset-spell.js_

```js
module.exports.plugins = [
  [
    require("remark-lint"),
    require("remark-retext"),
    require("unified")()
      .use(require("retext-english"))
      .use(require("retext-spell"))
  ]
];
```

the in the cli

```bash
remark . --use ./remark-preset-spell.js
```

**Comment by stephenmoloney** [comment]
@ChristianMurphy 

So basically the solution is to create a plugin - that seems like a good approach..

**Comment by wooorm** [comment]
Yes, it’s indeed possible through a plugin / preset!
And `.remarkrc` files are presets as well (and can be written in JS if named `.remarkrc.js`)!

**Comment by barlock** [comment]
How can I control the error code from the spell checker? Adding `[2]` in places doesn't seem to work and I can't quite figure out the syntax for using it with `unified-lint-rule`.

**Comment by wooorm** [comment]
@barlock That’s an issue for [retext-spell](https://github.com/retextjs/retext-spell), which doesn’t support different error codes.

**Comment by keplersj** [comment]
For anyone else that encounters this issue while Googling how to integrate `retext` with `remark` in the future, I've created a `remark-lint` preset that integrates many `retext` plugins with `remark`. It solves my use-case of some very basic automated proofreading in my lint pipeline. It's available as [`remark-preset-lint-retext-english`](https://github.com/keplersj/remark-preset-lint-retext-english) on npm.

**Comment by stephenmoloney** [comment]
Nice @keplersj. I never got around to it. Thank you for sharing.
