### ISSUE TITLE
feature_request(linting): exceptions

### ISSUE THREAD

**Issue by Kristinita** [remarkjs/remark-lint#202]
### 1. Summary

It would be nice, if remark-lint will support exceptions for third-party extensions without the need to disable the rules completely.

### 2. Argumentation

Users can use Markdown tools, plugins and so on (for example, I use [**Python Markdown**](https://github.com/Python-Markdown/markdown) and [**Pelican**](https://www.pelican.com/)), that make Markdown syntax non-valid for remark rules. It would be nice, if remark will support exceptions for specific rules.

### 3. Examples

Extensions:

1. [**EscapeAll**](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/) — escape any symbol
1. [**Pelican jtable**](https://github.com/burakkose/just_table) — simple table syntax
1. [**Markdown admonition**](https://python-markdown.github.io/extensions/admonition/) — add admonition syntax

Extensions syntax in file below.

I want to use rules `no-inline-padding`, `no-shortcut-reference-link`, `no-undefined-references` and `code-block-style` in all cases, except when I use the extensions above. At the time I need disable these rules. It would be nice, if would be possible set remark, that third-party extensions and remark-link no conflict.

### 4. Data

+ `Kira_remark-lint__non-valid_constructions.md`

```markdown
# remark-lint

## no-inline-padding

- *Time: 7 14 \* \* \* \** — crontab time for 14:07. If you want 14:24, you need: *Time: 24 14 \* \* \* \**.

## no-shortcut-reference-link and no-undefined-references

[jtable]
Kira|Goddess
[/jtable]

## code-block-style

!!! hint
    Kira

    ![Goddess](https://i.imgur.com/5Q7z7Mk.jpg)

```

+ `.remarkrc.yaml`:

```yaml
plugins:
  preset-lint-recommended:
  preset-lint-markdown-style-guide:

  lint-no-file-name-irregular-characters: false
  lint-no-file-name-mixed-case: false
  lint-maximum-line-length: false
```

### 5. Steps to reproduce

```text
remark Kira_remark-lint__non-valid_constructions.md --no-stdout
```

### 6. Expected behavior

No warnings.

### 7. Actual behavior

```text
D:\Kristinita>remark Kira_remark-lint__non-valid_constructions.md --no-stdout
Kira_remark-lint__non-valid_constructions.md
   5:26-5:84  warning  Don’t pad `emphasis` with inner spaces   no-inline-padding           remark-lint
     9:1-9:9  warning  Use the trailing [] on reference links   no-shortcut-reference-link  remark-lint
     9:1-9:9  warning  Found reference to undefined definition  no-undefined-references     remark-lint
  11:1-11:10  warning  Use the trailing [] on reference links   no-shortcut-reference-link  remark-lint
  11:1-11:10  warning  Found reference to undefined definition  no-undefined-references     remark-lint
  18:1-18:45  warning  Code blocks should be fenced             code-block-style            remark-lint

‼ 6 warnings

```

Thanks.

**Comment by ChristianMurphy** [comment]
> It would be nice, if remark-lint will support exceptions for third-party extensions without the need to disable the rules completely

Remark and RemarkLint support this through parser plugins, which allow Remark to handle new  syntax.
Some examples of this are:
* [Frontmatter](https://github.com/remarkjs/remark-frontmatter)
* [Katex Math](https://github.com/rokt33r/remark-math)
* and the [Zmarkdown plugins](https://github.com/zestedesavoir/zmarkdown/tree/master/packages)

> I want to use rules `no-inline-padding`, `no-shortcut-reference-link`, `no-undefined-references` and `code-block-style` in all cases, except when I use the extensions above. At the time I need disable these rules. It would be nice, if would be possible set remark, that third-party extensions and remark-link no conflict.

* [**Pelican jtable**](https://github.com/burakkose/just_table) — simple table syntax

can be supported through https://github.com/dimerapp/remark-macro.

These two do not have a plugin yet:

* [**EscapeAll**](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/) — escape any symbol
* [**Markdown admonition**](https://python-markdown.github.io/extensions/admonition/) — add admonition syntax

But could have a plugin created, so remark-lint would understand how to parse the Python style syntax, and wouldn't have conflicts currently being seen.

For some inspiration on how these could work: [fix-guillemets](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-fix-guillemets) is similar to EscapeAll in that it overrides default remark behavior, [captions](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-captions) is similar to admonition in that it looks for a starting marker then parses the text block after.

**Comment by wooorm** [comment]
@Kristinita Yes, as @ChristianMurphy mentions the solution here would be outside of remark-lint, but rather in remark land itself!

If you’re interested and could use some help with writing your own plugins, Spectrum is a good place to get it!

**Comment by Kristinita** [comment]
@ChristianMurphy, `type:question`

> can be supported through <https://github.com/dimerapp/remark-macro>

I add and set remark-macro → I run remark-lint. Will remark-lint ignore `no-shortcut-reference-link` and `no-undefined-references` for `[jtable]` construction?

I read remark-macro description → it seems to me that nothing will change.

Thanks.

**Comment by wooorm** [comment]
Try it out, it should!

**Comment by Kristinita** [comment]
@woorm , `type:question`

Did you try to add behavior to remark, similar [**as in Markdownlint**](https://github.com/DavidAnson/markdownlint#configuration)?

Example of expected behavior:

```markdown

<!-- remark-disable code-block-style -->

!!! hint
    Kira

    ![Goddess](https://i.imgur.com/5Q7z7Mk.jpg)

<!-- remark-enable code-block-style -->

```

Specific rule will ignore for specific block.

Thanks.

**Comment by ChristianMurphy** [comment]
@Kristinita Comment based configuration is a feature of remark-lint.
See the configuration guide in _readme.md_ https://github.com/remarkjs/remark-lint#configuring-remark-lint

```md
# Hello

<!--lint disable no-duplicate-headings-->

## Hello

<!--lint enable no-duplicate-headings-->

### Hello
```

**Comment by Kristinita** [comment]
@ChristianMurphy , sorry, I didn't notice it at first.

Thanks.
