### ISSUE TITLE
no-undefined-references flags […]

### ISSUE THREAD

**Issue by davidchambers** [remarkjs/remark-lint#207]
```console
$ npm install remark-cli@6.0.1 remark-lint-no-undefined-references@1.0.3

$ echo 'foo [...] bar' >README.md

$ node_modules/.bin/remark --use remark-lint-no-undefined-references -- README.md
foo [...] bar
README.md
  1:5-1:10  warning  Found reference to undefined definition  no-undefined-references  remark-lint

⚠ 1 warning
```

I think I understand the problem. Certain Markdown parsers permit `[x]` as shorthand for `[x][]`, which in turn is shorthand for `[x][x]`, so `...` in the example above is being treated as a link identifier.

Could we provide an option to skip such “links”? I'd like to be able to use _[…]_ when eliding a portion of a quoted passage. In the interim, what do you recommend as a workaround?

**Comment by davidchambers** [comment]
> In the interim, what do you recommend as a workaround?

Replacing `[…]` with `\[…]` solves the problem, although it isn't pretty.

In my view, `[…]` and `[...]` deserve to be treated specially so as not to be flagged. I'll be happy to submit a pull request if you agree.

**Comment by wooorm** [comment]
The problem here is that if you now define [...], everything will become a link! Probably won't happen, but it's not what you want or expect. That's what this rule does: warn you about that possibility!

**Comment by davidchambers** [comment]
Fair point. I think treating `[x]` as shorthand for `[x][]` is a mistake, but that wasn't your decision. ;)

**Comment by wooorm** [comment]
I agree, but that's markdown! My decision was to add a rule for it saying that you shouldn't use it!

If you do know what you're doing, it's of course fine, like all style decisions, so if you want to create an exception, I'd accept a PR!
