### ISSUE TITLE
Is the Git tag 6.0.5 for remark-lint missing?

### ISSUE THREAD

**Issue by ybiquitous** [remarkjs/remark-lint#224]
Hello, thank you for this nice tool!

Currently, I'm confusing that the Git tag `6.0.5` for remark-lint seems missing. 🤔 

The tag page is not found:
https://github.com/remarkjs/remark-lint/releases/tag/6.0.5

On the other hand, the version `6.0.5` has been published on the npm registry:
https://www.npmjs.com/package/remark-lint/v/6.0.5

It has been a long time since the release of version `6.0.5`, but is it possible to add the tag `6.0.5`?

**Comment by wooorm** [comment]
Correct, it’s missing. The publish was done here: https://github.com/remarkjs/remark-lint/commit/57b9eb10a337d1a253ccc005b4aaa87346bf880d.

It’s a benign patch, refactoring markdown and metadata. Out of curiosity, what is the reason you need the tag on GH?

**Comment by ybiquitous** [comment]
Thanks for the response. Because I want to generate useful links to each rule readme like:

https://github.com/remarkjs/remark-lint/blob/6.0.4/packages/remark-lint-code-block-style/readme.md

But sadly the following link to `6.0.5` is not found... 😢 

https://github.com/remarkjs/remark-lint/blob/6.0.5/packages/remark-lint-code-block-style/readme.md

**Comment by wooorm** [comment]
Solved by https://github.com/remarkjs/remark-lint/releases/tag/6.0.5!

**Comment by ybiquitous** [comment]
Thank you so much! 😊
