### ISSUE TITLE
remark-lint-table-pipe-alignment: Ignore last column

### ISSUE THREAD

**Issue by m-mohr** [remarkjs/remark-lint#226]
### Subject of the feature

It would be great if `remark-lint-table-pipe-alignment` could get an option to ignore last column. 

Usually we format our tables as follows:
```
| Path                                                                     | Content-Type Header | Description |
| ------------------------------------------------------------------------ | ------------------- | ----------- |
| `GET /collections/{collectionID}/versions`                               | `application/json`  | Returns a catalog response with links to all versions of a given collection. |
| `GET /collections/{collectionID}/versions/{versionId}`                   | `application/json`  | Returns a collection record. |
| `GET /collections/{collectionID}/items/{featureId}/versions`             | `application/json`  | Returns a catalog response with links to all versions of a given item. |
| `GET /collections/{collectionID}/items/{featureId}/versions/{versionId}` | `application/json`  | Returns an item record. |
```

We don't format the last column as it's not required for any following columns. 

### Expected behaviour

Maybe an option such as "ignoreLastColumn: true/false" with default set to false.

**Comment by wooorm** [comment]
Hmm, I| get where you’re coming from, but it seems like a bit of an edge case, as if we do that, then someone will ask: well, I want the middle row unaligned!

Would it work for y’all if you’d not align tables at all?

**Comment by m-mohr** [comment]
Well, I guess there's a good argument for the last column, not sure for the middle. Although you could also do something like `ignoreColumn: -1` (i.e. last) or `ignoreColumn: 0` (first). Then the middle column guy can configure it.

Not aligning tables is pretty bad looking and not an option for us. For now we removed the whole rule.

**Comment by wooorm** [comment]
This rule supports the common case: to align, or not to align. I think it’s useful in most cases. If a different style makes more sense, that project can be maintained [externally](https://github.com/remarkjs/remark-lint#list-of-external-rules).
