### ISSUE TITLE
Add "description" property to a rule, so it can be used for documentation purposes

### ISSUE THREAD

**Issue by dietergeerts** [remarkjs/remark-lint#238]
### Subject of the feature

The "unified-lint-rule" interface

### Problem

While looking for a way to automatically update a "README.md" file of a remark-lint preset package with the rules it provides, I saw that from the rules, I only have the "displayName" at my disposal. If we could also have a "description", I could use this to put in the readme automatically, and then the docs of the preset will always be up-to-date. It may be more of an edge-case, but this ensures that the "docs" are closer to the code, which makes it easier to know what the rule should be doing when developing it too.

### Expected behaviour

Having a way to add a "description" (or other property name that "documents" the rule) to the rule, so it can be extracted for documentation purposes.

### Alternatives

As a workaround, I'm working on just doing a linting rule that checks based on the "displayName" that the rule is described in the "README.md" file, so that we don't forget to document it.

Other alternatives would be that we extract the documentation from the file where the rule is defined, but that would involve a lot of extra libraries, and so many ways of documenting rules, and thus the way to extract would be different depending on the rule.

I can't think of any other alternatives right now.

**Comment by wooorm** [comment]
Interesting!

Do you have package identifiers? If so: could you load `package.json` files? E.g., you could generate the readme / index from your `dependencies` in `package.json`?

**Comment by dietergeerts** [comment]
The rules are not separated with each a `package.json` file, so there is no way to get a description that way. I know just get the export, which is the list of rules, and work with that. So if they have a description, then the README file could be updated automatically with them. There could be other purposes than my use-case. I think of the rule readme files that are provided for Eslint linting rules, as they have a standardized way of explaining rules and give examples. So by adding a `description` property to the exported rules, we will have a more general way of retrieving that description.

**Comment by wooorm** [comment]
> I think of the rule readme files that are provided for Eslint linting rules, as they have a standardized way of explaining rules and give examples.

We also generate readmes from the source file, however, we use documentation comments in remark-lint, so as not to burden the size of the code with metadata. Basically everything surrounding a plugin or preset here, including `doc/rules.md`, to the list of presets in the main readme, is generated from the source.

> The rules are not separated with each a package.json file, so there is no way to get a description that way.

How then do you use these rules (and other plugins)? Can you share more what you’re doing?

**Comment by wooorm** [comment]
I don’t think adding descriptions, which could be pretty long, to each rule, is a good idea. It would increase bundle size significantly, and while uncommon in this case, I think the using unified in browsers at a small size is important.

While not the same, if you have the package name of a rule, you can access it’s `package.json`, and find a short description at the [`description`](https://github.com/remarkjs/remark-lint/blob/00a6312656d471c491faf6db7eeef46253aeb72c/packages/remark-lint-table-pipe-alignment/package.json#L4) field at runtime. Alternatively, with access to the file system, the JSDoc comments can be parsed to find the [`@fileoverview`](https://github.com/remarkjs/remark-lint/blob/00a6312656d471c491faf6db7eeef46253aeb72c/packages/remark-lint-table-pipe-alignment/index.js#L6-L26) (and other fields).
