### ISSUE TITLE
remark Executable missing from shell

### ISSUE THREAD

**Issue by mcandre** [remarkjs/remark-lint#247]
Hi, when I install remark, then the executable somehow fails to copy to the `npm bin` directory, and so never appears on PATH.

**Comment by ChristianMurphy** [comment]
@mcandre sorry you ran into a spot of trouble a few things:
1. this appears to be related to `remark` not `remark-lint`, please log issues directly on the package, not on a different package
2. This appears to be more of a question than a bug? https://github.com/remarkjs/remark/discussions is the best avenue for support
3. when logging issues please use the issue template, it is there for a reason.

For a next step, try removing `node_modules` and installing `remark` again, sometimes `npm` doesn't generate the `bin` if it gets interrupted some how.
For follow up questions/issues, please follow the recommendations above.
