### ISSUE TITLE
Documentation and example on how to create custom rules

### ISSUE THREAD

**Issue by floroz** [remarkjs/remark-lint#261]
### Subject of the feature

Documentation and example to help developers understand how to create custom rules as part of `remark-lint` plugin system.

### Problem

As I have started creating custom rules for our content writers who edit markdown/mdx on a daily basis, I've come across the absence of some practical examples and walkthrough, which I think would be extremely beneficial if immediately available as part of the documentation of this repo.

If these examples are already available, and I have missed them, I apologise and would be glad if you can point me in the right direction.

### Solution

If you feel this type of documentation is currently missing, or could benefit from some additional example or walkthrough, I'd be happy to contribute with a PR submitting a new section in the README **Creating your custom rule**.

I can use a real-world example of a rule I've written and also add a quick overview on how to unit test such feature.

**Comment by wooorm** [comment]
Hi there! Good idea.

This example is close to the essence of a remark lint rule: https://unifiedjs.com/learn/guide/create-a-plugin/.
As you’re offering though, a similar guide “Create a remark lint rule”, would indeed be useful to have. It could be linked to from this repo.

**Comment by floroz** [comment]
> Hi there! Good idea.
> 
> This example is close to the essence of a remark lint rule: https://unifiedjs.com/learn/guide/create-a-plugin/.
> As you’re offering though, a similar guide “Create a remark lint rule”, would indeed be useful to have. It could be linked to from this repo.

Nice!

If that works for you, I can put together a PR with a small section in the repo `readme.md` with a small guide in the`doc/` folder (i.e `/doc/create-custom-rule.md`)
