### ISSUE TITLE
Add `repository.directory` field to package.json

### ISSUE THREAD

**Issue by ybiquitous** [remarkjs/remark-lint#268]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I executed the `npm repo remark-lint` command on my terminal, but <https://github.com/remarkjs/remark-lint/tree/main> opens unexpectedly on my browser, instead of <https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint>.

I think it useful to open <https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint>,  like `@babel-core`.
For example, when executing `npm repo @babel-core`, <https://github.com/babel/babel/tree/master/packages/babel-core> opens.

We can say that to other packages in this mono repo, like `unified-lint-rule`.

See also:
- https://docs.npmjs.com/cli/v7/commands/npm-repo

### Solution

What about adding the `repository.directory` field to `package.json` of all the published packages, like [`@babel/core`](https://github.com/babel/babel/blob/e498bee10f0123bb208baa228ce6417542a2c3c4/packages/babel-core/package.json#L12-L16)?

For example:

https://github.com/remarkjs/remark-lint/blob/b9d38489b77454a506d0dd3958b7a770b5ae91be/packages/remark-lint/package.json#L16

```diff
-  "repository": "https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint",
+  "repository": {
+    "type": "git",
+    "url": "https://github.com/remarkjs/remark-lint.git",
+    "directory": "packages/remark-lint"
+  }
```

See also:
- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository

### Alternatives

I don't have any alternatives.

**Comment by ChristianMurphy** [comment]
Sounds like a good add, would you be interested in opening a PR adding the metadata to packages @ybiquitous?

**Comment by ybiquitous** [comment]
Yes, I'll open a PR today later.
