### ISSUE TITLE
Add url to vfile messages

### ISSUE THREAD

**Issue by remcohaszing** [remarkjs/remark-lint#272]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Various tools can render links for comparable tools (I.e. ESLint). `VFileMessage` supports already this. It would make sense for `remark-lint` rules to specify links as well.

### Solution

`unified-lint-rule` should support more metadata information, probably by making the first argument an object which supports more types of metadata, for extensibility in the future.

```js
const remarkLintCodeBlockStyle = lintRule(
  {
    origin: 'remark-lint:code-block-style',
    url: 'https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-code-block-style#readme',
  },
  () => {/* … */}
)
```

This would be a breaking change in `unified-lint-rule`. To make it non-breaking, `lintRule` could accept either a string or object.

### Alternatives

The URL could be a second argument. This would be breaking.

```js
const remarkLintCodeBlockStyle = lintRule(
  'remark-lint:code-block-style',
  'https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-code-block-style#readme',
  () => {/* … */}
)
```

The URL could be a third argument. This would be non-breaking.

```js
const remarkLintCodeBlockStyle = lintRule(
  'remark-lint:code-block-style',
  () => {/* … */},
  'https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-code-block-style#readme'
)
```

Each rule could set the URL manually. This would require no changes in `unified-lint-rule`.

```js
const remarkLintCodeBlockStyle = lintRule(
  'remark-lint:code-block-style',
  (tree, file) => {
    /* … */
    const message = file.message('Code blocks should be ' + option, node)
    message.url = 'https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-code-block-style#readme'
    /* … */
  },
)
```

**Comment by wooorm** [comment]
I like the primary solution!

**Comment by remcohaszing** [comment]
> I like the primary solution!

With or without support for defining the source directly as a string? IMHO a major version bump for `unified-lint-rule` isn’t a big deal since I believe it’s mostly used internally.

**Comment by wooorm** [comment]
"To make it non-breaking, lintRule could accept either a string or object."

Origin makes more sense than url as required here, because that's a main reason to use this package.
An object is nice if we're going to add more stuff later.
But there's no need to depreciate existing usage in my opinion.
