### ISSUE TITLE
`no-undefined-references`: support regex in `allow` option

### ISSUE THREAD

**Issue by sisp** [remarkjs/remark-lint#296]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The Markdown I'm linting contains undefined references because they are implicitly resolved by the documentation library I'm using (in my case the MkDocs extension [`mkdocstrings`](https://mkdocstrings.github.io/) via its [cross-references](https://mkdocstrings.github.io/usage/#cross-references) feature). I would like to support allowing undefined references according to a regex pattern, typically something like `^mylib\.` (which is a Python root package prefix in my case). 

### Solution

For this to work, the `allow` option would need to be extended to support regex patterns.

I imagine the `options` object could be extended to this type (TS syntax):

```ts
type Options = {
  allow: Array<string | { pattern: string }>
}
```

If this proposal gets accepted, I'd be happy to submit a PR.

### Alternatives

Without supporting a regex pattern, I can only disable the linter:

```markdown
<!-- lint disable no-undefined-references -->
[`Object 1`][full.path.object1]
<!-- lint enable no-undefined-references -->
```

But that's a bit tedious to do everywhere in the docs.

**Comment by JounQin** [comment]
I think it's a good-to-have feature personally. 👍

**Comment by sisp** [comment]
I'll prepare a PR then. :slightly_smiling_face:

**Comment by wooorm** [comment]
Why an object w/ `pattern` field? Should a regex be supported?
If you have pattern as a string, what about regex flags?

**Comment by sisp** [comment]
@wooorm Do you mean this instead?

```ts
type Options = {
  allow: Array<string | RegExp>
}
```

What do you mean by "regex flags"?

**Comment by JounQin** [comment]
Regex flags means `i`, `g`, `u`, etc.

And `RegExp` type is not allowed in JhSON.

**Comment by sisp** [comment]
Thanks, that makes sense now! :+1:

**Comment by JounQin** [comment]
> u, might not be needed either, identifiers are typically ASCII?

I just understand this part.

**Comment by wooorm** [comment]
I don’t understand what you mean, Joun.

**Comment by JounQin** [comment]
> I don’t understand what you mean, Joun.

Oh, sorry, I *don't* understand why identifiers are always ASCII.

**Comment by wooorm** [comment]
> Oh, sorry, I don't understand why identifiers are always ASCII.

They don’t have to be. They typically are. Just like variable names in JavaScript and `id` attributes in HTML.

> Here, I think we need to explicitly differentiate between a literal string and a regex string.

Yes, I agree. But wanted to show them nonetheless.

**Comment by sisp** [comment]
So, what's the syntax then?

1.  ```ts
    type Options = {
      allow: Array<string | RegExp | { pattern: string }>
    }
    ```

1.  ```ts
    type Options = {
      allow: Array<string | RegExp | [pattern: string, flags?: string]>
    }
    ```

**Comment by wooorm** [comment]
I think the first is good, and we can go with case-insensitive always. If needed, we can add a `caseSensitive?: bool` field later, or add a `flags` field?

I am not sure about the name. Perhaps `source`? The benefit of this is that a regex also has a source, so it mimics that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/source.

**Comment by JounQin** [comment]
> Just like variable names in JavaScript and id attributes in HTML.

For CJK markdown content, It's not true. The id could always contain CJK characters.

**Comment by sisp** [comment]
I've submitted a PR.

**Comment by JounQin** [comment]
> > Just like variable names in JavaScript and id attributes in HTML.
> 
> For CJK markdown content, It's not true. The id could always contain CJK characters.

@wooorm Do you think this worth to be considered?

**Comment by wooorm** [comment]
> Do you think this worth to be considered?

I don’t understand what you want to consider.

I feel like you are arguing against something that I am not saying.

I am not saying unicode characters are not used. I am saying ASCII is typically used.

This is about an `u` flag. I don’t think we need a `u` flag now. We can always add flags if needed later.
If you believe a `u` flag is needed now, please come up with an example that would be broken with this proposal and an `u` flag would solve. Preferably a real world example of how you’d like to use this new feature, with readmes you write.

**Comment by JounQin** [comment]
> This is about an u flag. I don’t think we need a u flag now. We can always add flags if needed later.
> If you believe a u flag is needed now, please come up with an example that would be broken with this proposal and an u flag would solve. Preferably a real world example of how you’d like to use this new feature, with readmes you write.

Sure.

My own projects are always using English, but for documents in my business, CJK words are always used.

For example, links like <https://example.com?pageId=1#id-【内部路由支持双栈】UX设计文档-源文件>, and it references would contain CJK characters like `[源文件]: xxx`. So for consistency, if `u` flag could be supported at the first commit, that would be great IMO.

---

Of course.

> We can always add flags if needed later.

It is still an acceptable option to me, I'm just asking should be considered it now.

**Comment by wooorm** [comment]
> So for consistency, if u flag could be supported at the first commit, that would be great IMO.

How would you use this feature with such identifiers? In what regex do you need the `u` flag?

**Comment by JounQin** [comment]
I just realized specific CJK characters can used directly without `u` flag.

Not real case, but I can imagine a `u` flag would be useful to ignore all emojis in definitions for cases like @sisp's.

**Comment by wooorm** [comment]
> can used directly withou

Yes, that is my main point. regexes are in most cases fine with unicode. 

> would be useful to ignore all emojis in definitions

I agree that it might be useful in the future, but for now I’d say: let’s first wait for people that need this, for an actual use case!

**Comment by wooorm** [comment]
Thanks @sisp! [Released](https://github.com/remarkjs/remark-lint/releases/tag/remark-lint-no-undefined-references%404.2.0)!
