### ISSUE TITLE
Better configuration for individual rules?

### ISSUE THREAD

**Issue by slavafomin** [remarkjs/remark-lint#302]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hello!

I'm configuring Remark programmatically using TypeScript:

```ts
import { remark } from 'remark';
import remarkPresetLintMarkdownStyleGuide from 'remark-preset-lint-markdown-style-guide';
import remarkLintNoConsecutiveBlankLines from 'remark-lint-no-consecutive-blank-lines';

const processor = (remark()
  .use(remarkPresetLintMarkdownStyleGuide)
  .use(remarkLintNoConsecutiveBlankLines, false)
);
```

And I have two problems with it:

1. You can't set configuration or disable an individual rule without adding dependency for it in your `package.json`. In the example above I have to additionally install `remark-lint-no-consecutive-blank-lines` and import it as `remarkLintNoConsecutiveBlankLines` just to set a config for it. This is very boilerplate and somewhat ridiculous because `remark-preset-lint-markdown-style-guide` already has a dependency for this rule. Not to mention that it can cause problems when the version of the installed packages will mismatch between project and the preset package.

2. The declaration types for rule configuration are not resolved, which make them be treated as `any`. This just kills all the benefits of using TypeScript in the first place.

### Solution

The better API would be:

```ts
import { remark } from 'remark';
import remarkPresetLintMarkdownStyleGuide from 'remark-preset-lint-markdown-style-guide';

const processor = (remark()
  .use(remarkPresetLintMarkdownStyleGuide({
    // This should be type safe
    lintNoConsecutiveBlankLines: false,
    anotherPlugin: {
      option1: true,
      option2: 'value',
    }
  }))
);
```

### Alternatives

At least this should work (no need to install dependency and import it):

```ts
import { remark } from 'remark';
import remarkPresetLintMarkdownStyleGuide from 'remark-preset-lint-markdown-style-guide';

const processor = (remark()
  .use(remarkPresetLintMarkdownStyleGuide)
  .use('remark-lint-no-consecutive-blank-lines', false)
);
```

**Comment by wooorm** [comment]
Hi there!

This behavior is expected.

> somewhat ridiculous

No, it’s expected. There are different trade offs with different APIs, and this system has the best trade offs for the uses cases where unified works.

> The declaration types for rule configuration are not resolved

This seems like a separate problem, because they should be resolved, and not `any`. The types are defined and shipped: https://github.com/remarkjs/remark-lint/blob/cabbe86d1bd12ab5120196474ff08731644142d3/packages/remark-lint-no-consecutive-blank-lines/package.json#L31

> The better API would be

I don’t think it’s better. Because it doesn’t allow multiple presets to be used.

> At least this should work

That would require Node.js, it would break browser support.
There are ways around that with a different API, but it would still make everything slower for everyone.

**Comment by slavafomin** [comment]
> I don’t think it’s better. Because it doesn’t allow multiple presets to be used.

How so?

**Comment by slavafomin** [comment]
> This seems like a separate problem, because they should be resolved, and not `any`.

The option types (probably) can't be resolved, due to the call signature of the `use` method.

**Comment by wooorm** [comment]
> How so?

Different presets will include the same plugins. Plugins will have different options. Options have to be resolved (later configuration will be merged over earlier configuration)

> due to the call signature of the use method.

I don’t know what you mean. The rule is typed. The preset is typed. And unified is typed

**Comment by slavafomin** [comment]
> they should be resolved

My bad, they actually are.
