### ISSUE TITLE
Rule no-undefined-references triggers on markdown checklists

### ISSUE THREAD

**Issue by AfroThundr3007730** [remarkjs/remark-lint#311]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Using a list like this one:

- [x] Do thing
- [ ] Do other thing
- [ ] Do final thing

### Expected behavior

The rule doesn't trigger on checklists.

### Actual behavior

The rule triggers on checklists.

**Comment by wooorm** [comment]
Task lists are GFM features, not in markdown by default. You need to enable GFM features to use GFM features. Use remark-gfm!

**Comment by AfroThundr3007730** [comment]
Thanks for the info, I'll look into using that.
