### ISSUE TITLE
quiet flag ignored when using single-file

### ISSUE THREAD

**Issue by Hufschmidt** [remarkjs/remark-lint#313]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.1.2

### Steps to reproduce

First of all, thank you for everyone that contributed to this software and the awesome defaults, you doing great work. :)

It seems like I found a (rather minor) bug, as it seems the `--quiet` flag is ignored when running remark against a single file instead of a path/directory or file-glob with multiple files.

For example when running remark-lint on this project using:
`npx remark --use remark-lint --quiet readme.md`

Compare this to running it as:
`npx remark --use remark-lint --quiet .`
or
`npx remark --use remark-lint --quiet '*.md'`

Now delete `changelog.md` such that only the `readme.md` file remains and try 
`npx remark --use remark-lint --quiet '*.md'` 
again.

### Expected behavior

Remark-Lint should only output any linting errors and warnings.

### Actual behavior

Remark-Lint does output the linting errors and warning, but also prints the whole file content to stdout, regardless of the `--quiet` flag.

Note that this only seems to happen when directing remark-lint to a single file either directly or using a glob that only matches one file, this does not seems to happen when pointing to a directory or using file-globs with multiple files as actual target.

### Runtime

nodejs 18.18.2

### Package manager

npm 10.5.0

### OS

Linux (Manjaro)

### Build and bundle tools

None, technically using typescript in project were I noticed issue.

**Comment by ChristianMurphy** [comment]
Welcome @Hufschmidt! 👋 
Sorry you ran into some confusion.
That isn't related to remark lint and is expected.

That comes from unified aarms.
The quiet option refers specifically to messages https://github.com/unifiedjs/unified-args?tab=readme-ov-file#--quiet

When a single file is passed it does indeed write to stout, if you'd like to turn that off use `--no-stdout`
https://github.com/unifiedjs/unified-args?tab=readme-ov-file#--stdout
